# -*- coding: utf-8 -*-
# Created by Luis Enrique Fuentes Plata

version: "3.8"

networks:
  default:
    driver: bridge
    name: ${NETWORK_NAME}
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  api-checkpoint:
    build: .
    container_name: api-checkpoint
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - GIN_MODE=release
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "1111:1111"
