# -*- coding: utf-8 -*-
# Created by Luis Enrique Fuentes Plata

version: "3.8"

networks:
  default:
    driver: bridge
    name: ${NETWORK_NAME}
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  api-checkpoint:
    build: .
    container_name: api-checkpoint
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    stdin_open: true
    tty: true
    restart: always
    ports:
      - :1111
